### ISSUE TITLE
vk2

### ISSUE THREAD

**Issue by emlai** [emlai/how-bad#1]
http://tsoha.github.io/#/viikko2#top

- [x] Suunnittele käyttöliittymäsi ja toteuta niistä staattiset HTML-sivut. Muista lisätä linkit toteuttamiisi sivuihin reposi <code>README.md</code>-tiedostoon. <strong>(1,5p)</strong>
 - [x] Suunnittele etusivu</li>
 - [ ] Suunnittele listaussivut</li>
 - [ ] Suunnittele muokkaus- ja esittelysivut</li>
- [x] Ota tietokanta käyttöön ja dokumentoi se. <strong>(1,5p)</strong>
 - [x] Lisää dokumentaatioon <a href="http://advancedkittenry.github.io/dokumentaatio-ohje.html#j%C3%A4rjestelm%C3%A4n-tietosis%C3%A4lt%C3%B6">järjestelmän tietosisältö</a> osio ja <a href="http://advancedkittenry.github.io/dokumentaatio-ohje.html#relaatiotietokantakaavio">relaatiotietokantakaavio</a></li>
 - [x] Lisää tietokantataulujen pystytyslauseet <code>create_tables.sql</code>-tiedostoon</li>
 - [x] Lisää tietokantataulujen poistolauseet <code>drop_tables.sql</code>-tiedostoon</li>
 - [ ] Lisää testidatan lisäyslauseet <code>add_test_data.sql</code>-tiedostoon</li>
- [x] <strong>Pushaa kaikki tekemäsi muutokset repoosi!</strong>

**Comment by emlai** [comment]
@tuutuu Tein tälläsen ni voidaa merkitä mitä ollaa tehty ja nähä mitä pitää tehä :bomb:

**Comment by tuutuu** [comment]
cool hobbes

**Comment by emlai** [comment]
thanks bubbles

**Comment by tuutuu** [comment]
# computer science is best
