### ISSUE TITLE
vk4

### ISSUE THREAD

**Issue by tuutuu** [emlai/how-bad#5]
- [ ] Lisää malliluokkaasi metodi tietokohteen olion muokkaamiselle (esim. update)- ja poistolle (esim. destroy). (1p)
- [ ] Lisää käyttäjälle mahdollisuus muokkaukseen ja poistoon lisäämällä kontrolleriin tarvittavat metodit ja toteuttamalla tarvittavat näkymät. Muokkausnäkymä on luultavasti lisäysnäkymää muistuttava lomake ja poisto voi tapahtua painiketta painamalla esimerkiksi tietokohteen esittely- tai listaussivulla. (0,5p)
- [ ] Lisää malliisi tarvittavat validaattorit ja estä kontrollereissa virheellisten syötteiden lisääminen tietokantaan. Muista näyttää lomakkeissa virhetilanteissa virheilmoitukset ja täyttää kentät käyttäjän antamilla syötteillä. (0,5p)
- [x] Toteuta malliluokka sovelluksen käyttäjälle ja toteuta käyttäjän kirjautuminen. Toteuta get_user_logged_in-metodi ja käytä tarvittaessa kirjautuneen käyttäjän tietoa hyväksi näkymissä ja malleissa. (0,5p)
- [x] Kirjoita alustava käynnistys- / käyttöohje dokumentaatioosi. Lisää myös reposi README.md tiedostoon käyttäjätunnus ja salasana, jolla ohjaaja voi kirjautua sisään sovellukseesi. (0.5p)
- [x] Pushaa kaikki tekämäsi muutokset repoosi!

**Comment by tuutuu** [comment]
ಠ८̯ಠ

**Comment by emlai** [comment]
# <s>ಠ</s>८̯<s>ಠ</s>
