### ISSUE TITLE
vk5

### ISSUE THREAD

**Issue by tuutuu** [emlai/how-bad#7]
# koodattavaa läpi yön 

- [x] Toteuta käyttäjän uloskirjautuminen ja estä kirjautumattoman käyttäjän pääsy sivuille, jotka vaativat kirjautumisen. (1p)
- [ ] Edistä sovellustasi ja pidä koodi siistinä noudattamalla selkeää kansiorakennetta ja järkevää nimeämistä tiedostojen, luokkien ja metodien nimissä. Vaatimuksena on, että ainakin kahdelle tietokohteelle on toteutettu sivuja. Kaikkia CRUD-nelikon osia ei kuitenkaan tarvitse toteuttaa, listaus- ja esittelysivut uudelle tietokohteelle riittävät hyvin. Lisäksi kaikkien toimintojen tulee toimia ja virhetilanteissa käyttäjälle täytyy antaa järkeviä virheilmoituksia. (1p)
- [ ] Lisää dokumentaatioosi järjestelmän-yleisrakenne-osio ja käyttöliittymän ja järjestelmän komponentteja kuvaa kaavio. (1p)
- [ ] Kirjoita koodikatselmointi (vapaaehtoinen). (0-2p)
- [ ] Pushaa kaikki tekämäsi muutokset repoosi!

**Comment by emlai** [comment]
Totally done…
